import { User, Post, Comment, Notification } from '@/types/social';

// Mock users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    username: 'alexj',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop',
    bio: 'Digital creator & photographer 📸 | Travel enthusiast ✈️',
    followers: 12500,
    following: 560,
    posts: 340,
    isFollowing: true,
  },
  {
    id: '2',
    name: 'Taylor Smith',
    username: 'taylors',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    bio: 'UX Designer | Coffee lover ☕ | Dog mom 🐶',
    followers: 8900,
    following: 340,
    posts: 120,
    isFollowing: false,
  },
  {
    id: '3',
    name: 'Jordan Williams',
    username: 'jordanw',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    bio: 'Software Engineer | Open source contributor 💻',
    followers: 15600,
    following: 780,
    posts: 210,
    isFollowing: true,
  },
  {
    id: '4',
    name: 'Morgan Lee',
    username: 'morganl',
    avatar: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=100&h=100&fit=crop',
    bio: 'Food blogger 🍜 | Recipe developer 🍳',
    followers: 22400,
    following: 420,
    posts: 560,
    isFollowing: false,
  },
];

// Mock posts
export const mockPosts: Post[] = [
  {
    id: '1',
    userId: '1',
    user: mockUsers[0],
    content: 'Just captured this amazing sunset at the beach! 🌅 #sunset #beach #photography',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
    likes: 245,
    comments: 32,
    shares: 12,
    bookmarks: 18,
    createdAt: '2023-06-15T14:30:00Z',
    liked: true,
    bookmarked: false,
  },
  {
    id: '2',
    userId: '2',
    user: mockUsers[1],
    content: 'New coffee spot opened downtown! The latte art is incredible ☕️ #coffee #latteart #citylife',
    likes: 189,
    comments: 24,
    shares: 8,
    bookmarks: 42,
    createdAt: '2023-06-14T10:15:00Z',
    liked: false,
    bookmarked: true,
  },
  {
    id: '3',
    userId: '3',
    user: mockUsers[2],
    content: 'Just shipped a new feature for our open source project! Check it out on GitHub 🚀 #opensource #coding #webdev',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop',
    likes: 320,
    comments: 45,
    shares: 28,
    bookmarks: 67,
    createdAt: '2023-06-13T16:45:00Z',
    liked: true,
    bookmarked: true,
  },
  {
    id: '4',
    userId: '4',
    user: mockUsers[3],
    content: 'Tried a new recipe today - miso ramen with soft boiled eggs 🍜 #ramen #recipe #foodie',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&h=600&fit=crop',
    likes: 512,
    comments: 67,
    shares: 34,
    bookmarks: 89,
    createdAt: '2023-06-12T19:20:00Z',
    liked: false,
    bookmarked: false,
  },
];

// Mock comments
export const mockComments: Record<string, Comment[]> = {
  '1': [
    {
      id: '1',
      postId: '1',
      userId: '2',
      user: mockUsers[1],
      content: 'This is absolutely stunning! 🤩',
      likes: 12,
      createdAt: '2023-06-15T15:45:00Z',
      replies: [
        {
          id: '2',
          postId: '1',
          userId: '1',
          user: mockUsers[0],
          content: 'Thank you! It was a magical moment 🌅',
          likes: 5,
          createdAt: '2023-06-15T16:20:00Z',
          replies: [],
        },
      ],
    },
    {
      id: '3',
      postId: '1',
      userId: '3',
      user: mockUsers[2],
      content: 'The colors are incredible! What camera did you use?',
      likes: 8,
      createdAt: '2023-06-15T17:30:00Z',
      replies: [],
    },
  ],
  '2': [
    {
      id: '4',
      postId: '2',
      userId: '1',
      user: mockUsers[0],
      content: 'Which spot is this? I need to try it!',
      likes: 15,
      createdAt: '2023-06-14T11:30:00Z',
      replies: [],
    },
  ],
  '3': [
    {
      id: '5',
      postId: '3',
      userId: '4',
      user: mockUsers[3],
      content: 'This is exactly what I needed for my project! Thanks for sharing 🙌',
      likes: 22,
      createdAt: '2023-06-13T18:15:00Z',
      replies: [],
    },
  ],
  '4': [
    {
      id: '6',
      postId: '4',
      userId: '2',
      user: mockUsers[1],
      content: 'This looks delicious! Recipe please? 😋',
      likes: 34,
      createdAt: '2023-06-12T20:45:00Z',
      replies: [
        {
          id: '7',
          postId: '4',
          userId: '4',
          user: mockUsers[3],
          content: 'Of course! I\'ll post the full recipe tomorrow 📝',
          likes: 18,
          createdAt: '2023-06-12T21:10:00Z',
          replies: [],
        },
      ],
    },
  ],
};

// Mock notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    type: 'like',
    content: 'Taylor Smith liked your post',
    read: false,
    createdAt: '2023-06-15T15:45:00Z',
    relatedUser: mockUsers[1],
    relatedPost: mockPosts[0],
  },
  {
    id: '2',
    userId: '1',
    type: 'comment',
    content: 'Jordan Williams commented on your post',
    read: true,
    createdAt: '2023-06-15T17:30:00Z',
    relatedUser: mockUsers[2],
    relatedPost: mockPosts[0],
  },
  {
    id: '3',
    userId: '1',
    type: 'follow',
    content: 'Morgan Lee started following you',
    read: false,
    createdAt: '2023-06-14T09:15:00Z',
    relatedUser: mockUsers[3],
  },
  {
    id: '4',
    userId: '1',
    type: 'mention',
    content: 'Alex Johnson mentioned you in a comment',
    read: true,
    createdAt: '2023-06-13T12:30:00Z',
    relatedUser: mockUsers[0],
    relatedPost: mockPosts[2],
  },
];
